function MessagePage() {
    return (
        <div className="message">
            <h1>Here's a little message from me to the most wonderful girl in the whole world.</h1>
            <div className="message-container">
                <p>
                    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deserunt dignissimos aperiam inventore libero, dolorum repellat iusto voluptas et veniam harum ea esse rerum cumque architecto optio? Facere, ducimus ea! Magni?
                    Quia consequuntur exercitationem repellendus esse possimus doloribus ex mollitia incidunt quis? Facere animi incidunt quod aspernatur suscipit, nostrum provident, voluptatum fugit, assumenda repellendus perspiciatis atque sequi beatae in nesciunt veritatis.
                    Aliquam sequi laudantium sit obcaecati explicabo autem recusandae culpa dicta animi repellat voluptate quam, et inventore saepe praesentium dolorum debitis. At debitis dolor corporis delectus magni ratione ab officiis nisi!
                    Rerum corrupti modi officia deleniti natus. Possimus, recusandae soluta commodi nostrum pariatur fugiat, rem dicta accusantium sint a id omnis eos cumque amet unde aspernatur quia voluptatibus voluptate praesentium illum.
                    Eaque dicta quia error animi, non nesciunt explicabo quisquam vel quas, sapiente voluptas facilis asperiores dolore pariatur quaerat quidem eos architecto eum repellat. Nam saepe illo ducimus a animi vitae.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae harum assumenda voluptate beatae non esse placeat, totam laboriosam est eveniet incidunt soluta rem vitae ullam accusantium maiores obcaecati reiciendis saepe.
                    Vitae, sint deleniti quia earum quas rerum. Impedit veritatis molestias, illo eligendi quas expedita atque nemo, nisi rerum saepe consequatur unde voluptate facere aliquid sint reprehenderit assumenda! Voluptates, eos neque.
                    Quasi, error eius. Dolorum corporis recusandae sequi error eaque harum quibusdam placeat illum explicabo, accusamus ut earum assumenda amet tempora debitis suscipit quis itaque quas impedit quisquam animi eveniet ab.
                    Omnis blanditiis odit dolorem quidem ipsa corrupti modi assumenda, fugit, quos aspernatur sit aut impedit suscipit atque, ducimus at alias eaque sed qui officia culpa quia numquam quaerat aliquam. Quasi?
                    Fugiat eveniet esse earum, dolores odio totam obcaecati iste perferendis tempora fuga architecto provident animi ex nulla reprehenderit ducimus tempore eligendi officiis pariatur eius dicta labore. Autem eius veniam expedita.
                    Accusamus deleniti nulla quasi iusto? Quia veritatis commodi doloremque vitae reiciendis, nostrum ab delectus possimus quaerat culpa est sit placeat quibusdam alias deserunt, obcaecati minima rem! Corrupti, quod consectetur? Quos.
                    Deserunt, veritatis blanditiis enim accusantium necessitatibus consequuntur! Harum tempora ipsam, molestias minima asperiores assumenda modi pariatur reiciendis! Rem placeat nisi soluta, ducimus aspernatur, illum corrupti possimus iste asperiores, enim eius.
                    Quos explicabo, ex natus ipsum iusto laborum molestias totam officia consequatur quia numquam delectus nihil omnis hic rem voluptate sint cumque debitis possimus necessitatibus aspernatur sed! Possimus beatae sed quibusdam?
                    Nihil vitae tenetur totam pariatur. Commodi laboriosam quae illo voluptates alias corrupti magnam amet consequatur quam. Nisi, dolor. Minus nihil laudantium officiis, hic similique numquam quidem aliquam vero autem nulla.
                    Rem, facere voluptas sapiente blanditiis deserunt porro adipisci dolorum! Ipsum a quos reiciendis odit? Modi excepturi est et placeat dignissimos, consequuntur veritatis eaque animi accusantium, deserunt commodi? Dolorum, facilis suscipit!
                    Mollitia a accusamus ipsum eum, corporis alias nisi voluptatibus maiores beatae inventore fugit eius fugiat enim, id sit. Consequatur omnis incidunt vitae nobis distinctio odio ipsa non, iure aperiam laudantium!
                    Dolore in est aut rerum cupiditate commodi quisquam ipsa? Fugit voluptatum distinctio et a ullam hic iusto debitis fuga repellendus perspiciatis, explicabo quas deleniti iure ad ex at repellat consequatur?
                    Mollitia sint ipsum dolorem itaque quas nobis adipisci porro placeat repellendus, cum illo repudiandae pariatur, quidem ex veritatis nemo. Iure unde quaerat eaque quia delectus ullam commodi hic obcaecati cum.
                    Excepturi rem iusto magnam nisi officia. Perspiciatis accusamus veritatis ratione, molestiae quam porro dolore provident assumenda blanditiis numquam doloremque accusantium eveniet ab, architecto ut, eligendi magnam. Tempore dicta laborum eligendi.
                    Consequatur officiis debitis vero quisquam voluptatum modi ipsam odit inventore, iste sapiente quos accusamus nisi laborum beatae voluptates tempora perspiciatis? Cum consequatur in maxime sunt modi corporis molestiae reprehenderit magnam?
                    Nostrum deserunt delectus perspiciatis, mollitia repellat quam architecto quod. Ad corporis, facilis eius distinctio unde pariatur optio saepe repellat dolore deserunt rem neque repellendus! Esse blanditiis animi et voluptas perspiciatis.
                    Ex pariatur necessitatibus sequi vitae autem voluptatibus consequatur nesciunt voluptatem quae. Consectetur veniam quasi aperiam eligendi assumenda dolor aut, voluptate ullam quae eos, voluptatum nisi? Similique eum mollitia repellendus expedita.
                    Vero ipsa maxime temporibus ad impedit quaerat voluptatem commodi deleniti hic porro vitae architecto ea, tenetur nesciunt eligendi modi recusandae dolores, doloribus facilis nihil! Aspernatur eligendi in eius voluptatum architecto!
                    Quibusdam cupiditate tenetur doloribus voluptas laboriosam ipsa sequi ea officiis aut recusandae ipsum voluptate debitis, magnam magni libero a perspiciatis nemo incidunt? Hic, quas debitis ratione explicabo voluptatem iusto recusandae!
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda atque quas temporibus vel tempore similique cum error culpa ad facere? Dolore voluptate esse adipisci dolorum nesciunt earum, vero suscipit. Excepturi?
                    Cupiditate ullam magni exercitationem ipsum sed rerum voluptatibus inventore consequuntur eligendi corporis velit incidunt quibusdam ut quidem aliquam possimus, quis nesciunt eveniet, numquam omnis hic repellendus temporibus dolorem sint! Omnis?
                    Voluptate illum maxime veniam fugiat. Saepe necessitatibus facilis, perspiciatis harum error voluptatum nulla animi. Doloremque ullam inventore reprehenderit! Quo porro voluptas hic quod voluptatem molestiae aliquam nemo unde! Nesciunt, consequuntur!
                    Cumque officiis veniam, repellendus sint nesciunt reiciendis iusto saepe accusantium ipsam provident recusandae quidem a. Sit, placeat! Temporibus dicta blanditiis, culpa eaque earum porro omnis itaque magni, et tenetur repellendus.
                    Praesentium, ipsam natus alias odio vel veritatis officiis fugiat debitis consequatur error expedita sint. Ex, nesciunt et eveniet perspiciatis exercitationem sapiente natus iure harum facilis, eaque quae sint voluptates obcaecati!
                    Ullam voluptates ut architecto quae culpa totam voluptatum nemo id voluptate repudiandae provident minima, necessitatibus esse eligendi, corporis, cumque officiis libero. Quidem culpa cupiditate autem natus dolore deleniti veniam? Incidunt!
                    Atque aliquam obcaecati commodi quia quisquam. Natus et iure suscipit quae ut neque harum ratione distinctio quis doloribus magni, officia soluta odio, vitae deleniti eius consequuntur eum minus ab sit.
                    Officiis, nobis consequatur vel deserunt sequi quas suscipit velit nam magni, soluta porro a est, repudiandae molestias unde. Commodi a alias neque! Distinctio tenetur nobis, nesciunt porro molestiae officiis libero!
                    Quia natus pariatur ratione sit doloribus mollitia quis saepe, accusantium beatae, maiores amet dolorem molestiae, dignissimos quaerat repudiandae reprehenderit perspiciatis soluta! Sequi nihil voluptatum laboriosam! Iure sint ad quod earum!
                    Sit repellat in, illo fugit ipsum ab, odio rem porro velit non placeat suscipit! Optio tenetur temporibus harum voluptatibus, praesentium dolor inventore quas nulla eveniet laboriosam officiis in ex sed?
                    Deserunt beatae veniam minima, rem accusantium velit natus totam possimus tempora quisquam maiores nostrum cum voluptate, impedit fugiat repellat maxime corrupti assumenda. Vel voluptate magni cumque earum culpa itaque dolores?
                    Fuga laboriosam eum amet excepturi optio praesentium, quis iste fugit labore explicabo cumque culpa suscipit provident quidem in eaque dicta odio vero commodi! Quas at alias quibusdam voluptates harum numquam!
                    A voluptatibus vitae veritatis enim obcaecati atque dolorem dolores quaerat ad consequuntur maxime voluptas ut accusamus, minus, saepe molestiae, unde excepturi quos optio placeat! Necessitatibus adipisci architecto culpa quo neque?
                    Ipsum, commodi amet! Vero corrupti voluptatem eaque magnam, reiciendis modi labore consectetur, praesentium doloribus dignissimos esse veritatis! Illum earum temporibus a vel harum sequi, debitis veritatis facere sapiente non soluta.
                    Maiores, adipisci quo assumenda rerum aliquid nisi at quas? Neque minus molestiae repellat quaerat. Nisi illum vero, ad corporis ab earum soluta vel voluptate officiis perferendis assumenda ex iusto perspiciatis.
                    Autem pariatur, reiciendis odio commodi est natus cumque quod ad ipsam corporis numquam ullam non quo doloribus nesciunt quia eaque ut, soluta, eveniet nisi cum omnis incidunt nihil praesentium! Possimus?
                    Neque necessitatibus odit minus magnam! Ea amet ut et soluta aperiam. In, recusandae consequuntur. Id harum voluptates distinctio perferendis eius. Autem accusamus tempora expedita voluptate quisquam ipsa voluptatibus soluta fugiat.
                    Pariatur, error distinctio autem officia blanditiis animi quod recusandae. Eum repellat odio ullam magnam rem esse totam error, dignissimos aliquam excepturi vitae deserunt, natus blanditiis ipsum non molestias fugiat expedita.
                    Dolore, veritatis optio. Voluptate et eligendi aliquid, obcaecati cumque culpa voluptatibus. Totam pariatur illo nam consequatur ab dolorem ad a delectus ea laboriosam, ratione recusandae odio iure, velit odit doloremque?
                    Tempore, molestiae voluptatem nisi suscipit eos qui quo numquam ab commodi exercitationem nam dolorum aperiam magnam, sunt nemo, voluptatum corporis eligendi cum rerum ullam temporibus? Dolores consequuntur et vero ullam.
                    A veniam placeat facere perspiciatis perferendis quas, doloribus tenetur beatae! Nam vero necessitatibus debitis molestiae. Impedit quae quisquam necessitatibus, hic ipsum inventore, eius dolorum assumenda corporis tempora at suscipit sequi.
                    Cumque nobis similique sit facilis dignissimos excepturi ut, accusamus blanditiis placeat enim eius tempora deserunt obcaecati quo culpa asperiores. Labore nisi impedit quia voluptas reprehenderit exercitationem officia doloremque voluptates odio!
                    Magni, est nostrum ad, minima ex, aspernatur doloremque quis voluptatem quia ratione aliquid odit! Saepe, odit iure. Voluptatibus, sint qui ad dolor magnam accusamus ea. Eos qui facilis quos explicabo.
                    Sit qui nulla quasi non dolorem deleniti, neque aspernatur velit magni dolorum obcaecati consequatur quis porro commodi quos facere totam? Dolorum eos dolorem ex adipisci deserunt, tenetur expedita quidem sed?
                    Aliquid, laboriosam! Fugit nostrum adipisci cumque reprehenderit expedita repudiandae, enim dolores non possimus ipsum illum dolor natus, modi aut est. Doloribus nulla delectus facere magnam ipsum ducimus error deleniti repellendus.
                    Voluptatum quisquam facilis excepturi soluta. Sit reiciendis commodi totam dolores voluptates beatae harum qui itaque assumenda neque, quasi, quibusdam magni! Quo dolores consectetur enim quos maxime non, expedita nam at.
                    Nulla dignissimos placeat deserunt reiciendis dolor blanditiis molestiae sit officia aperiam nesciunt. Atque amet tempore totam natus itaque. Quam quae assumenda vitae dolore facilis voluptates minima laboriosam, cupiditate quos blanditiis.
                    Minus ea saepe similique aliquam quas fugiat quasi necessitatibus, magni delectus inventore laborum nisi voluptatibus corporis rerum vero recusandae. Asperiores, vitae nihil ducimus itaque blanditiis aperiam temporibus quis ut? Nihil?
                    Neque enim ipsam unde aperiam expedita, accusantium tempore eligendi recusandae commodi nemo rem ullam aut quidem illum, temporibus ab reiciendis error eius, vero eos labore officia quo nobis. Iste, veniam.
                    Blanditiis possimus magnam cum dolorum in deleniti nobis exercitationem atque provident nostrum explicabo fugiat quis, at harum optio consectetur omnis! Facere commodi eum saepe assumenda? Voluptatum rem neque excepturi eveniet?
                </p>
            </div>
        </div>
    )
}

export default MessagePage;